### ISSUE TITLE
Utworzenie CSV dla raportu

### ISSUE THREAD

**Issue by qdesigner1985** [Aroo-dev/Task-Reporter#6]

**Comment by StysiekDev** [comment]
Utworzono kolumny tabeli dla raportu

[Plik CSV dla tworzenia raportu.xls](https://github.com/user-attachments/files/15747543/Plik.CSV.dla.tworzenia.raportu.xls)

**Comment by StysiekDev** [comment]
Zmiana rozszerzenia pliku na .csv





[SampleTaskLog.csv](https://github.com/user-attachments/files/15747739/SampleTaskLog.csv)
